const APP_ROUTES = {
    webpage: {
        _: '',
        pricing: 'pricing',
        patients: 'patients',
        providers: 'providers',
        about: 'about',
        demo: 'demo',
        findMyMeds: 'find-my-meds',
        dashboard: 'dashboard',
        privacy: 'privacy',
        termsOfService: 'InStockRxTerms',
    },
    product: {
        _: '',
        app: 'app',
        auth: 'auth',
        clinician: 'clinician',
        nearBySearches: 'near-by-searches',
        patient: 'patient',
        signIn: 'sign-in',
        signUp: 'sign-up',
        forgotPassword: 'forgot-password',
        newSearch: 'new-search',
        payments: 'payments',
        activeSearches: 'active-searches',
        medicationDetails: 'medication-details',
        previousSearches: 'previous-searches',
        dashboard: 'dashboard',
        resetPassword: 'reset-password',
        editPatientsProfile: 'edit-patients-profile',
        searchInfo: 'search-info',
        searchStatus: 'search-status',
    },
};

export default APP_ROUTES;
